version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ptsp-kemenag-backend
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env.local

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ptsp-kemenag-frontend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    depends_on:
      - backend
