version: '3.8'

services:
  ptsp-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ptsp-kemenag-app
    restart: always
    ports:
      - "3000:3000"
      - "8080:8080"
    env_file:
      - .env.local
