CREATE TYPE "public"."ptsp_app_role" AS ENUM('user', 'admin_ptsp', 'kepala_kantor', 'kasubag_tu', 'super_admin');--> statement-breakpoint
CREATE TYPE "public"."ptsp_request_status" AS ENUM('draft', 'submitted', 'under_review', 'revision_required', 'rejected', 'approved', 'completed', 'spam');--> statement-breakpoint
CREATE TYPE "public"."ptsp_notification_type" AS ENUM('info', 'success', 'warning', 'error');--> statement-breakpoint
CREATE TABLE "ptsp_profiles" (
	"id" uuid PRIMARY KEY NOT NULL,
	"full_name" text,
	"email" text,
	"phone" text,
	"address" text,
	"role" "ptsp_app_role" DEFAULT 'user' NOT NULL,
	"created_at" timestamp (6) with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp (6) with time zone DEFAULT now() NOT NULL,
	"unit_kerja" text,
	"is_verified" boolean DEFAULT true,
	"permissions" jsonb DEFAULT '["ringkasan","pengajuan","dokumen_hasil"]'::jsonb,
	"avatar_url" text,
	CONSTRAINT "ptsp_profiles_email_unique" UNIQUE("email"),
	CONSTRAINT "ptsp_profiles_phone_unique" UNIQUE("phone")
);
--> statement-breakpoint
CREATE TABLE "ptsp_role_permissions" (
	"role" varchar PRIMARY KEY NOT NULL,
	"permissions" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"updated_at" timestamp (6) with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "ptsp_service_form_fields" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "service_form_fields_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"service_item_id" bigint NOT NULL,
	"label" text NOT NULL,
	"name" text NOT NULL,
	"type" text NOT NULL,
	"placeholder" text,
	"is_required" boolean DEFAULT false NOT NULL,
	"options" text,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp (6) with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp (6) with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ptsp_service_items" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "service_items_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"service_id" bigint NOT NULL,
	"name" text NOT NULL,
	"slug" text NOT NULL,
	"description" text,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp (6) with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp (6) with time zone DEFAULT now() NOT NULL,
	"sort_order" integer DEFAULT 0,
	"estimated_time" text DEFAULT '1-3 Hari Kerja'
);
--> statement-breakpoint
CREATE TABLE "ptsp_service_requirements" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "service_requirements_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"service_item_id" bigint NOT NULL,
	"document_name" text NOT NULL,
	"description" text,
	"is_required" boolean DEFAULT true NOT NULL,
	"allowed_extensions" text DEFAULT 'pdf,jpg,jpeg,png',
	"max_file_size_mb" integer DEFAULT 5 NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp (6) with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp (6) with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ptsp_services" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "services_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"slug" text NOT NULL,
	"description" text,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp (6) with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp (6) with time zone DEFAULT now() NOT NULL,
	"role_owner" text,
	"sort_order" integer DEFAULT 0,
	CONSTRAINT "ptsp_services_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "ptsp_generated_documents" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "generated_documents_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"request_id" uuid NOT NULL,
	"file_name" text NOT NULL,
	"file_path" text NOT NULL,
	"generated_by" uuid,
	"generated_at" timestamp (6) with time zone DEFAULT now() NOT NULL,
	"created_at" timestamp (6) with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp (6) with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "ptsp_generated_documents_request_id_unique" UNIQUE("request_id")
);
--> statement-breakpoint
CREATE TABLE "ptsp_service_request_answers" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "service_request_answers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"request_id" uuid NOT NULL,
	"field_id" bigint,
	"field_name" text NOT NULL,
	"field_value" text,
	"created_at" timestamp (6) with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp (6) with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ptsp_service_request_documents" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "service_request_documents_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"request_id" uuid NOT NULL,
	"requirement_id" bigint,
	"file_name" text NOT NULL,
	"file_path" text NOT NULL,
	"file_type" text,
	"file_size" bigint,
	"created_at" timestamp (6) with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp (6) with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ptsp_service_request_reviews" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "service_request_reviews_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"request_id" uuid NOT NULL,
	"reviewer_id" uuid NOT NULL,
	"status" "ptsp_request_status" NOT NULL,
	"notes" text,
	"created_at" timestamp (6) with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ptsp_service_requests" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"service_id" bigint NOT NULL,
	"service_item_id" bigint NOT NULL,
	"request_number" text NOT NULL,
	"status" "ptsp_request_status" DEFAULT 'draft' NOT NULL,
	"submitted_at" timestamp (6) with time zone,
	"approved_at" timestamp (6) with time zone,
	"rejected_at" timestamp (6) with time zone,
	"completed_at" timestamp (6) with time zone,
	"revision_note" text,
	"rejection_reason" text,
	"created_at" timestamp (6) with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp (6) with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "ptsp_service_requests_request_number_unique" UNIQUE("request_number")
);
--> statement-breakpoint
CREATE TABLE "ptsp_activity_logs" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "activity_logs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"request_id" uuid,
	"actor_id" uuid,
	"action" text NOT NULL,
	"notes" text,
	"created_at" timestamp (6) with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ptsp_audit_logs" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"admin_id" uuid NOT NULL,
	"action" text NOT NULL,
	"entity_type" text,
	"entity_id" text,
	"details" jsonb,
	"ip_address" text,
	"created_at" timestamp (6) with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ptsp_system_status" (
	"id" text PRIMARY KEY DEFAULT 'heartbeat' NOT NULL,
	"last_ping" timestamp (6) with time zone DEFAULT now() NOT NULL,
	"notes" text DEFAULT 'Keep-alive trigger',
	"maintenance_mode" boolean DEFAULT false,
	"maintenance_message" text DEFAULT 'Sistem sedang dalam pemeliharaan berkala. Silakan kembali beberapa saat lagi.',
	"maintenance_started_at" timestamp (6) with time zone,
	"maintenance_started_by" uuid
);
--> statement-breakpoint
CREATE TABLE "ptsp_notifications" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid,
	"type" "ptsp_notification_type" DEFAULT 'info' NOT NULL,
	"title" text NOT NULL,
	"message" text NOT NULL,
	"is_read" boolean DEFAULT false NOT NULL,
	"link" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ptsp_guest_book" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "guest_book_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"visit_date" date NOT NULL,
	"guest_name" text NOT NULL,
	"whatsapp" text NOT NULL,
	"institution_type" text NOT NULL,
	"institution_name" text,
	"intended_officer" text NOT NULL,
	"purpose" text NOT NULL,
	"created_at" timestamp (6) with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp (6) with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ptsp_appointments" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "appointments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"appointment_date" date NOT NULL,
	"appointment_time" text NOT NULL,
	"guest_name" text NOT NULL,
	"whatsapp" text NOT NULL,
	"institution_type" text NOT NULL,
	"institution_name" text,
	"intended_officer" text NOT NULL,
	"purpose" text NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"created_at" timestamp (6) with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp (6) with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ptsp_feedbacks" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "feedbacks_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"email" text NOT NULL,
	"phone" text NOT NULL,
	"content" text NOT NULL,
	"created_at" timestamp (6) with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp (6) with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "ptsp_profiles" ADD CONSTRAINT "ptsp_profiles_id_users_id_fk" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ptsp_service_form_fields" ADD CONSTRAINT "ptsp_service_form_fields_service_item_id_ptsp_service_items_id_fk" FOREIGN KEY ("service_item_id") REFERENCES "public"."ptsp_service_items"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ptsp_service_items" ADD CONSTRAINT "ptsp_service_items_service_id_ptsp_services_id_fk" FOREIGN KEY ("service_id") REFERENCES "public"."ptsp_services"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ptsp_service_requirements" ADD CONSTRAINT "ptsp_service_requirements_service_item_id_ptsp_service_items_id_fk" FOREIGN KEY ("service_item_id") REFERENCES "public"."ptsp_service_items"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ptsp_generated_documents" ADD CONSTRAINT "ptsp_generated_documents_request_id_ptsp_service_requests_id_fk" FOREIGN KEY ("request_id") REFERENCES "public"."ptsp_service_requests"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ptsp_generated_documents" ADD CONSTRAINT "ptsp_generated_documents_generated_by_ptsp_profiles_id_fk" FOREIGN KEY ("generated_by") REFERENCES "public"."ptsp_profiles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ptsp_service_request_answers" ADD CONSTRAINT "ptsp_service_request_answers_request_id_ptsp_service_requests_id_fk" FOREIGN KEY ("request_id") REFERENCES "public"."ptsp_service_requests"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ptsp_service_request_answers" ADD CONSTRAINT "ptsp_service_request_answers_field_id_ptsp_service_form_fields_id_fk" FOREIGN KEY ("field_id") REFERENCES "public"."ptsp_service_form_fields"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ptsp_service_request_documents" ADD CONSTRAINT "ptsp_service_request_documents_request_id_ptsp_service_requests_id_fk" FOREIGN KEY ("request_id") REFERENCES "public"."ptsp_service_requests"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ptsp_service_request_documents" ADD CONSTRAINT "ptsp_service_request_documents_requirement_id_ptsp_service_requirements_id_fk" FOREIGN KEY ("requirement_id") REFERENCES "public"."ptsp_service_requirements"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ptsp_service_request_reviews" ADD CONSTRAINT "ptsp_service_request_reviews_request_id_ptsp_service_requests_id_fk" FOREIGN KEY ("request_id") REFERENCES "public"."ptsp_service_requests"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ptsp_service_request_reviews" ADD CONSTRAINT "ptsp_service_request_reviews_reviewer_id_ptsp_profiles_id_fk" FOREIGN KEY ("reviewer_id") REFERENCES "public"."ptsp_profiles"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ptsp_service_requests" ADD CONSTRAINT "ptsp_service_requests_user_id_ptsp_profiles_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."ptsp_profiles"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ptsp_service_requests" ADD CONSTRAINT "ptsp_service_requests_service_id_ptsp_services_id_fk" FOREIGN KEY ("service_id") REFERENCES "public"."ptsp_services"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ptsp_service_requests" ADD CONSTRAINT "ptsp_service_requests_service_item_id_ptsp_service_items_id_fk" FOREIGN KEY ("service_item_id") REFERENCES "public"."ptsp_service_items"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ptsp_activity_logs" ADD CONSTRAINT "ptsp_activity_logs_request_id_ptsp_service_requests_id_fk" FOREIGN KEY ("request_id") REFERENCES "public"."ptsp_service_requests"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ptsp_activity_logs" ADD CONSTRAINT "ptsp_activity_logs_actor_id_ptsp_profiles_id_fk" FOREIGN KEY ("actor_id") REFERENCES "public"."ptsp_profiles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ptsp_audit_logs" ADD CONSTRAINT "ptsp_audit_logs_admin_id_ptsp_profiles_id_fk" FOREIGN KEY ("admin_id") REFERENCES "public"."ptsp_profiles"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ptsp_system_status" ADD CONSTRAINT "ptsp_system_status_maintenance_started_by_ptsp_profiles_id_fk" FOREIGN KEY ("maintenance_started_by") REFERENCES "public"."ptsp_profiles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ptsp_notifications" ADD CONSTRAINT "ptsp_notifications_user_id_ptsp_profiles_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."ptsp_profiles"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "ptsp_service_request_documents_request_id_requirement_id_key" ON "ptsp_service_request_documents" USING btree ("request_id","requirement_id");